language: node_js
node_js:
  - "node"

after_script:
  - gco gh-pages
  - git init
  - npm i
  - grunt html
  - grunt css
  - grunt uglify
  - rm -rf node_modules
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - gh-pages
